### ISSUE TITLE
How to generate log_jit file?

### ISSUE THREAD

**Issue by lst-oss** [01ChenQing/Qemu-tcg-log-viewer#1]
When I execute the command: 
"qemu-system-arm -M versatilepb -m 128 -kernel test.bin -nographic -d out_asm -D out_asm.txt"
I can only generate the Host directive file, which is not consistent with the log_jit format.

**Comment by 01ChenQing** [comment]
> When I execute the command: "qemu-system-arm -M versatilepb -m 128 -kernel test.bin -nographic -d out_asm -D out_asm.txt" I can only generate the Host directive file, which is not consistent with the log_jit format.

hi，这个项目是解析 qemu-user 的log用的 ，没有对 qemu-system 进行测试，看了下你的 repo ，国内的安全研究环境很差，iot漏挖工作是纯牛马，如果对iot很感兴趣，建议关注下 pwn2own的比赛目标，同时关注国外工作机会。
